apiVersion: v2
name: kubevirt-cdi
description: Install the Containerized Data Importer
type: application
version: 0.3.0
appVersion: "v1.63.1"
maintainers:
  - name: "cloudymax"
    email: "emax@cloudydev.net"
    url: "https://github.com/cloudymax/"
