apiVersion: v2
name: kubevirt-community-stack
description: Combined meta-chart for installing Kubevirt, its dependencies, and addons

type: application
version: 0.0.0
appVersion: "0.0.0"

maintainers:
  - name: "cloudymax"
    email: "emax@cloudydev.net"
    url: "https://github.com/cloudymax/"

dependencies:
- name: kubevirt-cdi
  alias: cdi
  version: 0.2.0
  repository: https://cloudymax.github.io/kubevirt-community-stack
- name: kubevirt
  alias: operator
  version: 0.2.8
  repository: https://cloudymax.github.io/kubevirt-community-stack
- name: kubevirt-manager
  alias: manager
  version: 0.2.1
  repository: https://cloudymax.github.io/kubevirt-community-stack
  condition: manager.enabled
- name: cluster-api-operator
  alias: capi
  version: 0.0.0
  repository: https://cloudymax.github.io/kubevirt-community-stack
  condition: capi.enabled
