{{ if eq .Values.existingConfigMap false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.secret_name }}-optimizer-script
  namespace: {{ .Values.namespace }}
data:
  optimize.sh: |
    {{ .Files.Get "scripts/cigen.sh" | nindent 4}}
{{- end }}
