{{- if eq .Values.serviceAccount.create true }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: secret-admin
 annotations: {}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
