---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secret_name }}-cleanup-job-sa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloud-init.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "0"
