{{- if eq .Values.serviceAccount.create true }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.secret_name }}-secret-admin
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloud-init.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
