{{ if eq .Values.existingConfigMap false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.secret_name }}-secret-script
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloud-init.labels" . | nindent 4 }}
data:
  secretgen.sh: |
    {{ .Files.Get "scripts/secretgen.sh" | nindent 4}}
{{- end }}
