apiVersion: v2
name: kubevirt-manager
description: Install the Kubevirt Manager UI

type: application
version: 0.3.0
appVersion: v1.5.3

maintainers:
  - name: "cloudymax"
    email: "emax@cloudydev.net"
    url: "https://github.com/cloudymax/"
