apiVersion: v2
name: kubevirt-manager
description: Install the Kubevirt Manager UI

type: application
version: 0.2.0
appVersion: 1.4.1

maintainers:
  - name: "cloudymax"
    email: "emax@cloudydev.net"
    url: "https://github.com/cloudymax/"
