apiVersion: v2
name: kubevirt
description: Deploy Kebivirt on Kubernetes
type: application
version: 0.5.0
appVersion: "v1.7.0"
maintainers:
  - name: "cloudymax"
    url: "https://github.com/cloudymax/"
