apiVersion: v2
name: kubevirt
description: Deploy Kebivirt on Kubernetes
type: application
version: 0.4.0
appVersion: "v1.6.2"
maintainers:
  - name: "cloudymax"
    url: "https://github.com/cloudymax/"
