{{- if eq .Values.cluster.provider "rke2" }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: {{ .Values.cluster.name }}-md-0
  namespace: {{ .Values.cluster.namespace }}
spec:
  template:
    spec:
      agentConfig: {}
      gzipUserData: false
{{- end }}
